service:
  name: rest-crud

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack: ${file(../../common.yml):custom.webpack}

provider:
  name: aws
  runtime: nodejs10.x

functions:
  index:
    handler: list.handle
    events:
      - http:
          method: get
          path: {object}
          cors: true
  create:
    handler: create.handle
    events:
      - http:
          method: post
          path: {object}
          cors: true
  read:
    handler: read.handle
    events:
      - http:
          method: get
          path: {object}/{id}
          cors: true
  update:
    handler: update.handle
    events:
      - http:
          path: {object}/{id}
          method: put
          cors: true
  delete:
    handler: delete.handle
    events:
      - http:
          path: {object}/{id}
          method: delete
          cors: true